logging:
  level:
  root: warn
spring:
  datasource:
    url: jdbc:mysql://172.18.231.40:8066/gtradedb?useUnicode=true&characterEncoding=utf-8
    username: gtrade
    password: trade123
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
