logging:
  level:
    root: DEBUG
  config: classpath:conf/logback-spring.xml
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
#    username: root
#    password: 123456
#    hikari:
#      driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8

